CREATE TABLE "Teams" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "color" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp,
  idCategory int
);

CREATE TABLE "Players" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" int,
  "name" varchar,
  "titular" bool,
  "idTeam" int,
  "present" bool,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "PlayerTarget" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPlayer" int,
  "idTarget" int,
  "idMatch" int,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "Targets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "Matches" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" varchar,
  "location" varchar,
  "minutes" int,
  "startTime" timestamp,
  "idCategory" int,
  "active" bool,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "MatchTeams" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idTeamLocal" int,
  "idTeamVisit" int,
  "idMatch" int,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "Scores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idTeam" int,
  "idPlayer" int,
  "idMatch" int,
  "scoreTime" timestamp,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

ALTER TABLE "Players" ADD FOREIGN KEY ("idTeam") REFERENCES "Teams" ("id");

ALTER TABLE "PlayerTarget" ADD FOREIGN KEY ("idPlayer") REFERENCES "Players" ("id");

ALTER TABLE "PlayerTarget" ADD FOREIGN KEY ("idTarget") REFERENCES "Targets" ("id");

ALTER TABLE "PlayerTarget" ADD FOREIGN KEY ("idMatch") REFERENCES "Matches" ("id");

ALTER TABLE "Matches" ADD FOREIGN KEY ("idCategory") REFERENCES "Categories" ("id");

ALTER TABLE "MatchTeams" ADD FOREIGN KEY ("idTeamLocal") REFERENCES "Teams" ("id");

ALTER TABLE "MatchTeams" ADD FOREIGN KEY ("idTeamVisit") REFERENCES "Teams" ("id");

ALTER TABLE "MatchTeams" ADD FOREIGN KEY ("idMatch") REFERENCES "Matches" ("id");

ALTER TABLE "Scores" ADD FOREIGN KEY ("idTeam") REFERENCES "Teams" ("id");

ALTER TABLE "Scores" ADD FOREIGN KEY ("idPlayer") REFERENCES "Players" ("id");

ALTER TABLE "Scores" ADD FOREIGN KEY ("idMatch") REFERENCES "Matches" ("id");

alter table "Teams" add column idCategory int;
alter table "Teams" add constraint fk_teams_categories foreign key (idCategory) references "Categories" (id);

insert into "Teams" values (1,'Club Dacte','asdasd');
insert into "Teams" values (2,'Club Portul','asdasd');

insert into "Categories" values (1,'Sub 15');
insert into "Categories" values (2,'Sub 12');
insert into "Categories" values (3,'Sub 17');

insert into "Matches" values (1,'3','Rosas',20,'2016-06-22 19:10:25-07',1);
insert into "Matches" values (2,'3','Rosas',20,'2016-06-22 21:10:25-07',2);



insert into "MatchTeams" values (1,1,2,1);
insert into "MatchTeams" values (2,2,1,2);

select * from "Matches" m ;
select * from "MatchTeams" mt ;
